import type { Metadata } from "next";
import { OnboardingProvider } from "@/context/OnboardingContext";
import { Stepper } from "./components/onboarding/Stepper";
import { ShieldCheck } from "lucide-react";

export const metadata: Metadata = {
  title: "On Boarding",
  description: "Generated by create next app",
};

export default function OnBoardingLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <OnboardingProvider>
        <section className="flex min-h-screen">
          <aside className="basis-[30%] hidden lg:flex w-72 bg-brand-navy text-white flex-col p-6 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full bg-white/5 opacity-50 pointer-events-none"></div>
            <div className="relative z-10 flex items-center gap-3 pl-1">
              <div className="p-2 bg-white/10 rounded-xl backdrop-blur-sm border border-white/10">
                <ShieldCheck className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold tracking-tight">Smart Link</span>
            </div>
            <Stepper />
          </aside>
          <div className="basis-[70%] flex justify-center items-center">{children}</div>
        </section>
      </OnboardingProvider>
    </div>
  );
}
