import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const Inter = localFont({
  src: [
    { path: "./fonts/Inter.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Inter-Italic.ttf", weight: "400", style: "italic" },
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Smart Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${Inter.variable}  antialiased`}>{children}</body>
    </html>
  );
}
